{
 "title": "Industrial IoT",
 "description": "Industrial IoT dashboard",
 "time": { "from": "2025-05-30T02:11:25.772Z", "to": "2025-05-30T14:11:25.772Z" },
 "refresh": "30s",
 "panels": [
  { "title": "Arduino 01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_01\" and r._field == \"data\")"
    }
   ]
  },
  {
   "title": "DR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_01\" and r._field == \"dr\")"
    }
   ]
  },
  {
   "title": "SF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_01\" and r._field == \"SF\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_01\" and r._field == \"frequency\")"
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_01\" and r._field == \"fCnt\")"
    }
   ]
  },
  {
   "title": "Confirmed Message",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_01\" and r._field == \"confirmed\")"
    }
   ]
  },
  { "title": "Arduino 02", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_02\" and r._field == \"data\")"
    }
   ]
  },
  {
   "title": "DR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_02\" and r._field == \"dr\")"
    }
   ]
  },
  {
   "title": "SF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_02\" and r._field == \"SF\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_02\" and r._field == \"frequency\")"
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_02\" and r._field == \"fCnt\")"
    }
   ]
  },
  {
   "title": "Confirmed Message",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_02\" and r._field == \"confirmed\")"
    }
   ]
  },
  { "title": "Arduino 03", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_03\" and r._field == \"data\")"
    }
   ]
  },
  {
   "title": "DR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_03\" and r._field == \"dr\")"
    }
   ]
  },
  {
   "title": "SF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_03\" and r._field == \"SF\")"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_03\" and r._field == \"frequency\")"
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_03\" and r._field == \"fCnt\")"
    }
   ]
  },
  {
   "title": "Confirmed Message",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"industrial_iot\")\r\n    |> range(start: -24h)\r\n    |> filter(fn: (r) => r._measurement == \"arduino_03\" and r._field == \"confirmed\")"
    }
   ]
  }
 ]
}